### ISSUE TITLE
French localization file contains improperly commented strings

### ISSUE THREAD

**Issue by KyrosKrane** [Dragnogd/Instance-Achievement-Tracker#12]
The French localization file has some lines commented out; but those lines contain a line break. The string terminator is on a second, unquoted line, which causes lua errors in the file. See e.g. lines 55-56 in Localization.frFR.lua.

The in-game lua error is:

```
25x InstanceAchievementTracker\Localization.frFR.lua:56: unfinished string near '",'


Locals:
```

**Comment by Dragnogd** [comment]
Resolved.
