### ISSUE TITLE
Azjol-Nerub missing from WotLK

### ISSUE THREAD

**Issue by aj672** [Dragnogd/Instance-Achievement-Tracker#14]
![image](https://user-images.githubusercontent.com/55977509/195248108-2f60de61-6edb-4a61-86b5-cdc597955da0.png)

Hey, I'm missing Azjol-Nerub from the list of instances. Is it just me?

**Comment by Dragnogd** [comment]
Thank you. This is fixed in for the next release.

**Comment by aj672** [comment]
Thank you @Dragnogd - great addon, and appreciate your work!
