### ISSUE TITLE
Option to not tracking unobtainable achievements

### ISSUE THREAD

**Issue by Bukama** [Dragnogd/Instance-Achievement-Tracker#16]
Yesterday I was doing Mechagon achievements with my groups, esp. the hard mode ("Keep DPS-ing and Nobody Explodes"). IAT was also tracking "Hertz Locker" which is the achievement for hard mode without anyone dying. When we killed the last boss and non of us has died during the run I realized that - even it's still possibly to track the achievement due the auto track of IAT - it's a Feats of Strength achievement now. That makes sense as it's in no way difficult with current level and gear.

So maybe an option to not tracking such achievements should be added and also maybe they should be marked as such in the "IAT dungeon journal"

**Comment by Dragnogd** [comment]
Thanks for the heads up. I have removed Hertz Locker from tracking/journal now that it is a feats of strength.
