### ISSUE TITLE
Shocking achievement in WoTLK Naxxramas

### ISSUE THREAD

**Issue by mariusch** [Dragnogd/Instance-Achievement-Tracker#17]
On first Polarity IAT will report that the achievement has failed, even when it is not.

ID for https://www.wowhead.com/wotlk/spell=28059/positive-charge is used when it should have been https://www.wowhead.com/wotlk/spell=28062/positive-charge. It is correct for Negative Charge.

From Warcraftlogs: 
![image](https://user-images.githubusercontent.com/3537273/201056362-1bee6b8b-6f15-44c1-a110-1f8ab1018921.png)

Please update L152 in LichKingRaids/Naxxramas.lua to `if (core.spellId == 28085 or core.spellId == 28062) and (core.type == "SPELL_DAMAGE" or core.type == "SPELL_MISSED") then`

Solves the bug that it incorrectly reports failure on first polarity and couldn't track the achievement. Thanks for a great addon!

**Comment by Dragnogd** [comment]
Thanks for investigating. This is fixed for the next release.
