### ISSUE TITLE
Incorrect fail message on Weapons of the Maruukai

### ISSUE THREAD

**Issue by KyrosKrane** [Dragnogd/Instance-Achievement-Tracker#19]
While running The Nokhud Offensive, we successfully completed the requirements for Weapons of the Maruukai, then killed the bosses. On ending the fight, we got our achievements, and simultaneously, IAT reported that we had failed.

![image](https://user-images.githubusercontent.com/458727/209641827-4ced58f0-88de-4fc4-adc8-d6ab59acb23a.png)

**Comment by Dragnogd** [comment]
Hopefully fixed this but if not will take another look.
