### ISSUE TITLE
Feature Request: Change Minimap Icon Color if Addon enabled/disabled

### ISSUE THREAD

**Issue by Nercus** [Dragnogd/Instance-Achievement-Tracker#4]
Pretty much like the title of the issue. Different color for the minimap for the diffrent states of the Option `Enable Addon`.

**Comment by Dragnogd** [comment]
Hi Nercus,
Thanks for the suggestion. I like the idea of being able to see the state of the addon at a glance from the minimap. I think it would be difficult to implement though unless I can find an identical icon with a different colour scheme. I will have a look though.

**Comment by Nercus** [comment]
The minimap wa icon changes color. Don't know what that color change is based on but you can look into that.

**Comment by Nercus** [comment]
Another (maybe better example): Using rightclick on the tooltip of the Rarity icon changes the icon as a whole.

**Comment by Dragnogd** [comment]
Added option in next release. Icon will go green when tracking is enabled. Red when tracking is disabled and darkened when addon is disabled. 
![image](https://user-images.githubusercontent.com/6664974/103101208-4f5e5200-460e-11eb-9874-9ec432ca2a9f.png)
![image](https://user-images.githubusercontent.com/6664974/103101211-5ab17d80-460e-11eb-9e0e-fa79921066c8.png)
![image](https://user-images.githubusercontent.com/6664974/103101215-600ec800-460e-11eb-9881-79dc7b8a05fa.png)
![image](https://user-images.githubusercontent.com/6664974/103101221-64d37c00-460e-11eb-8e98-b0081deef4de.png)
